### ISSUE TITLE
dtb build error

### ISSUE THREAD

**Issue by altmangood** [buglloc/nanopi-r5#1]
cd dtb
sh make_dtb.sh

when all file download and unzipped, to build dtb has this error:

```
_
Error: linux-6.1.18/arch/arm64/boot/dts/rockchip/rockchip-pinconf.dtsi:7.2-3 syntax error
FATAL ERROR: Unable to parse input tree
```

os: Ubuntu 18.04 LTS
dtc  1.4.3

is the build system env not good ? Which os should i use to build dtb?

**Comment by buglloc** [comment]
Just tested on a fresh Ubuntu 22.04 LTS - it seems to work as expected :)
```
$ sudo apt install -y device-tree-compiler gcc wget xz-utils
$ sh make_dtb.sh
[...]
build complete: rk3568-nanopi-r5.dtb
```

**Comment by altmangood** [comment]
Thanks, I change to Ubuntu 20.04 Focal ， it works well.

> build complete: rk3568-nanopi-r5.dtb
